[package]
name = "drone_swarm"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.8", features = ["std_rng"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
reed-solomon = "0.2"
aes-gcm = "0.9"
thiserror = "1.0"
lazy_static = "1.4"
